version: '3.8'

services:
  db:
    image: postgres:13
    container_name: blog_postgres_db
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: blog_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - blog_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  blog_network:
    driver: bridge